image: node:16.9.1

stages:
  - build
  - lint

build:
  stage: build
  before_script:
    - npm ci
  script:
    - echo "This job tests build"
    - npm run build:dev
  only:
    - merge_request

lint:
  stage: lint
  before_script:
    - npm ci
  script:
    - npm run lint
  only:
    - merge_request
